import 'package:estilo_neutral/features/search/domain/entities/inventario_item.dart';

/// Catálogo fijo para los tests de búsqueda (antes era el respaldo de la app).
const List<InventarioItem> catalogoDePrueba = [
  InventarioItem(
    id: 'p00000001',
    name: 'Camisa Oxford Manga Larga',
    marca: 'Tommy Hilfiger',
    modelo: 'Classic Fit',
    talla: 'M',
    cantidad: 15,
    precioUsd: 35.0,
  ),
  InventarioItem(
    id: 'p00000002',
    name: 'Pantalón Jean 501 Original',
    marca: "Levi's",
    modelo: 'Straight Leg',
    talla: '32',
    cantidad: 20,
    precioUsd: 45.0,
  ),
  InventarioItem(
    id: 'p00000003',
    name: 'Franela Dri-FIT Deportiva',
    marca: 'Nike',
    modelo: 'Training Legend',
    talla: 'L',
    cantidad: 30,
    precioUsd: 25.0,
  ),
  InventarioItem(
    id: 'p00000004',
    name: 'Chaqueta Impermeable Cortaviento',
    marca: 'Columbia',
    modelo: 'Glennaker Lake',
    talla: 'XL',
    cantidad: 8,
    precioUsd: 65.0,
  ),
  InventarioItem(
    id: 'p00000005',
    name: 'Zapatos Deportivos Running',
    marca: 'Adidas',
    modelo: 'Ultraboost Light',
    talla: '42',
    cantidad: 12,
    precioUsd: 110.0,
  ),
  InventarioItem(
    id: 'p00000006',
    name: 'Polo Piqué Algodón Premium',
    marca: 'Lacoste',
    modelo: 'L1212 Classic',
    talla: 'M',
    cantidad: 18,
    precioUsd: 55.0,
  ),
  InventarioItem(
    id: 'p00000007',
    name: 'Suéter Tejido Cuello Redondo',
    marca: 'Zara',
    modelo: 'Soft Knit',
    talla: 'S',
    cantidad: 14,
    precioUsd: 28.0,
  ),
  InventarioItem(
    id: 'p00000008',
    name: 'Bermuda Cargo Algodón',
    marca: 'Dockers',
    modelo: 'Cargo Utility',
    talla: '34',
    cantidad: 22,
    precioUsd: 32.0,
  ),
];
